version: "3.9"
services:
  dns-server:
    image: technitium/dns-server:latest
    ports:
      - "5380:5380/tcp" #DNS web console (HTTP)
      - "53:53/udp" #DNS service
      - "53:53/tcp" #DNS service
      # - "853:853/udp" #DNS-over-QUIC service
      # - "853:853/tcp" #DNS-over-TLS service
      # - "443:443/udp" #DNS-over-HTTPS service (HTTP/3)
      # - "443:443/tcp" #DNS-over-HTTPS service (HTTP/1.1, HTTP/2)
      # - "80:80/tcp" #DNS-over-HTTP service (use with reverse proxy or certbot certificate renewal)
      # - "8053:8053/tcp" #DNS-over-HTTP service (use with reverse proxy)
      # - "67:67/udp" #DHCP service
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65000
    volumes:
      - '/home/ismael/technitium/config:/etc/dns'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD-SHELL", "dig +short +retry=0 +norecurse @127.0.0.1 cloudflare.com || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    env_file:
      - stack.env

  # pangolin:
  #   image: fosrl/pangolin:latest
  #   volumes:
  #     - /home/ismael/pangolin/pangolin/config:/app/config
  #   deploy:
  #     replicas: 1
  #     restart_policy:
  #       condition: on-failure
  #   networks:
  #     - pangolin_net
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:3001/api/v1/"]
  #     interval: "3s"
  #     timeout: "3s"
  #     retries: 15 
  # gerbil:
  #   image: fosrl/gerbil:1.0.0
  #   deploy:
  #     replicas: 1
  #     restart_policy:
  #       condition: on-failure
  #   command:
  #     - --reachableAt=http://gerbil:3003
  #     - --generateAndSaveKeyTo=/var/config/key
  #     - --remoteConfig=http://pangolin:3001/api/v1/gerbil/get-config
  #     - --reportBandwidthTo=http://pangolin:3001/api/v1/gerbil/receive-bandwidth
  #   volumes:
  #     - /home/ismael/pangolin/gerbil:/var/config
  #   cap_add:
  #     - NET_ADMIN
  #     - SYS_MODULE
  #   networks:
  #     - pangolin_net
  #   ports:
  #     - target: 51820
  #       published: 51820
  #       protocol: udp
  #     - target: 21820
  #       published: 21820
  #       protocol: udp
  #     - target: 443
  #       published: 443
  #       protocol: tcp
  #     - target: 80
  #       published: 80
  #       protocol: tcp
  traefik:
    image: traefik:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    networks:
      - pangolin_net
    ports:
      - target: 443
        published: 443
        protocol: tcp
      - target: 80
        published: 80
        protocol: tcp
    secrets:
      - desec_token
    volumes:
      - /home/ismael/pangolin/traefik/config:/etc/traefik
      - /home/ismael/pangolin/traefik/letsencrypt:/letsencrypt
    command:
      - --configFile=/etc/traefik/traefik_config.yml
    env_file:
      - stack.env

networks:
  pangolin_net:
    driver: overlay
    attachable: true

secrets:
  desec_token:
    external: true
