version: "3.8"
services:
  shepherd:
    build: .
    image: containrrr/shepherd
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    env_file:
      - stack.env
