version: "3.9"
services:
  dns-server:
    image: technitium/dns-server:latest
    ports:
      - target: 5380 #DNS web console (HTTP)
        published: 5380
        protocol: tcp
        mode: host
      - target: 53 #DNS service
        published: 53
        protocol: tcp
        mode: host
      - target: 53 #DNS service
        published: 53
        protocol: udp
        mode: host
      # - "853:853/udp" #DNS-over-QUIC service
      # - "853:853/tcp" #DNS-over-TLS service
      # - "443:443/udp" #DNS-over-HTTPS service (HTTP/3)
      # - "443:443/tcp" #DNS-over-HTTPS service (HTTP/1.1, HTTP/2)
      # - "80:80/tcp" #DNS-over-HTTP service (use with reverse proxy or certbot certificate renewal)
      # - "8053:8053/tcp" #DNS-over-HTTP service (use with reverse proxy)
      # - "67:67/udp" #DHCP service
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65000
    volumes:
      - '/home/ismael/technitium/config:/etc/dns'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD-SHELL", "dig +short +retry=0 +norecurse @127.0.0.1 google.es || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    env_file:
      - stack.env
  ddns-updater:
    image: qmcgaw/ddns-updater
    volumes:
      - /home/ismael/ddns:/updater/data
    ports:
      - target: 8000
        published: 8008
        protocol: tcp
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    dns:
      - 192.168.1.250