version: "3.9"
services:
  linkding:
    image: sissbruecker/linkding:latest
    deploy:
      restart_policy:
        condition: any
    ports:
      - target: 9090
        published: 9090
        protocol: tcp
    volumes:
      - /home/ismael/linkding/data:/data
