version: "3.9"
services:
  linkwarden:
    image: ghcr.io/linkwarden/linkwarden:latest
    deploy:
      restart_policy:
        condition: any
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
    volumes:
      - /home/ismael/bookmarks/linkwarden/data:/data/data
  meilisearch:
    image: getmeili/meilisearch:v1.12.8
    volumes:
      - /home/ismael/bookmarks/melidata/data:/meili_data
