version: "3.9"
services:
  pangolin:
    image: fosrl/pangolin:latest
    volumes:
      - /home/ismael/pangolin/pangolin/config:/app/config
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - pangolin_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/v1/"]
      interval: "3s"
      timeout: "3s"
      retries: 15 
    secrets:
      - pangolin-server-secret
    env_file:
      - stack.env
  gerbil:
    image: fosrl/gerbil:1.0.0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    command:
      - --reachableAt=http://gerbil:3003
      - --generateAndSaveKeyTo=/var/config/key
      - --remoteConfig=http://pangolin:3001/api/v1/gerbil/get-config
      - --reportBandwidthTo=http://pangolin:3001/api/v1/gerbil/receive-bandwidth
    volumes:
      - /home/ismael/pangolin/gerbil:/var/config
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    networks:
      - pangolin_net
    ports:
      - target: 51820
        published: 51820
        protocol: udp
      - target: 21820
        published: 21820
        protocol: udp
  traefik:
    image: traefik:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    networks:
      - pangolin_net
    ports:
      - target: 443
        published: 443
        protocol: tcp
      - target: 80
        published: 80
        protocol: tcp
    secrets:
      - desec_token
    volumes:
      - /home/ismael/pangolin/traefik/config:/etc/traefik
      - /home/ismael/pangolin/traefik/letsencrypt:/letsencrypt
    command:
      - --configFile=/etc/traefik/traefik_config.yml
    env_file:
      - stack.env

networks:
  pangolin_net:
    driver: overlay
    attachable: true

secrets:
  desec_token:
    external: true
  pangolin-server-secret:
    external: true

