version: "3.9"
services:
  dns-server:
    image: technitium/dns-server:latest
    ports:
      - target: 5380 #DNS web console (HTTP)
        published: 5380
        protocol: tcp
        mode: host
      - target: 53 #DNS service
        published: 53
        protocol: tcp
        mode: host
      - target: 53 #DNS service
        published: 53
        protocol: udp
        mode: host
      #- target: 853 #DNS-over-QUIC service
      #  published: 853
      #  protocol: udp
      #  mode: host
      #- target: 853 #DNS-over-TLS service
      #  published: 853
      #  protocol: tcp
      #  mode: host
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65000
    volumes:
      - '/home/ismael/technitium/config:/etc/dns'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD-SHELL", "dig +short +retry=0 +norecurse @127.0.0.1 google.es || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    env_file:
      - stack.env