version: "3.8"
services:
  pi-hole:
    image: pihole/pihole:latest
    ports:
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      - target: 53
        published: 53
        protocol: udp
        mode: host
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - '/home/ismael/pi-hole/pi-hole:/etc/pihole'
      - '/home/ismael/pi-hole/pi-hole-dns:/etc/dnsmasq.d'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD-SHELL", "dig +short +norecurse +retry=0 @127.0.0.1 pi.hole || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    env_file:
      - stack.env
