version: "3.8"
services:
  pi-hole:
    image: pihole/pihole:latest
    ports:
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      - target: 53
        published: 53
        protocol: udp
        mode: host
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - '~/pi-hole/pi-hole:/etc/pihole'
      - '~/pi-hole/pi-hole-dns:/etc/dnsmasq.d'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    env_file:
      - stack.env
