services:
  redis-yamtrack:
    image: redis:8-alpine
    restart: unless-stopped
    env_file: .env.dockhand
    volumes:
      - redis-yamtrack:/data
    networks:
      - pangolin_net
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  yamtrack:
    image: ghcr.io/fuzzygrim/yamtrack
    restart: unless-stopped
    env_file: .env.dockhand
    ports:
      - "8010:8000/tcp"
    dns: 192.168.0.250
    environment:
      SECRET: ${YAMTRACK_SECRET}
      DB_PASSWORD: ${YAMTRACK_DB_PASSWORD}
      HARDCOVER_API: ${YAMTRACK_HARDCOVER_KEY}
      REDIS_URL: redis://redis-yamtrack:6379
      DB_HOST: 192.168.0.251
      DB_NAME: yamtrack
      DB_USER: yamtrack
      DB_PORT: "5433"
      TZ: Europe/Berlin
    networks:
      - pangolin_net
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://127.0.0.1:8000 || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
    depends_on:
      redis-yamtrack:
        condition: service_healthy

volumes:
  redis-yamtrack:

networks:
  pangolin_net:
    external: true
