services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    restart: unless-stopped
    group_add:
      - "992"
    entrypoint: []
    user: "1024:100"
    ports:
      - "3001:3001/tcp"
    volumes:
      - /home/ismael/uptimeKuma/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    healthcheck:
      test: node -e "require('http').get('http://127.0.0.1:3001').on('response',()=>process.exit(0)).on('error',()=>process.exit(1))"
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

networks:
  default:
    name: pangolin_net
