services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped
    entrypoint: []
    group_add:
      - "992"
    environment:
      HOMEPAGE_ALLOWED_HOSTS: 192.168.0.250:3002,homepage.ios-tools.dedyn.io,localhost:3002
    ports:
      - "3002:3000/tcp"
    volumes:
      - /home/ismael/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - pangolin_net
    healthcheck:
      test: wget -qO- http://127.0.0.1:3000/api/healthcheck || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s

networks:
  pangolin_net:
    external: true
