services:
  paperless-broker:
    image: docker.io/library/redis:8
    restart: unless-stopped
    env_file: .env.dockhand
    volumes:
      - paperless-redis:/data
    networks:
      - pangolin_net
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  paperless-webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    env_file: .env.dockhand
    ports:
      - "8998:8000/tcp"
    user: "1024:100"
    volumes:
      - /home/ismael/paperless/paperless/scripts:/usr/src/paperless/scripts
      - /home/ismael/paperless/paperless/data:/usr/src/paperless/data
      - /home/ismael/paperless/paperless/media:/usr/src/paperless/media
      - /home/ismael/paperless-ngx/export:/usr/src/paperless/export
      - /home/ismael/paperless-ngx/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_DBPASS: ${PAPERLESS_DBPASS}
      PAPERLESS_SOCIALACCOUNT_PROVIDERS: ${PAPERLESS_SOCIALACCOUNT_PROVIDERS}
      PAPERLESS_REDIS: redis://paperless-broker:6379
      PAPERLESS_DBHOST: 192.168.0.251
      PAPERLESS_DBPORT: "5433"
      PAPERLESS_TIME_ZONE: Europe/Madrid
      PAPERLESS_OCR_LANGUAGE: spa
      PAPERLESS_OCR_LANGUAGES: eng
      PAPERLESS_URL: https://paperless.ios-tools.dedyn.io
      PAPERLESS_APPS: allauth.socialaccount.providers.openid_connect
      PAPERLESS_LOGOUT_REDIRECT_URL: https://authentik.ios-tools.dedyn.io/application/o/paperless/end-session/
      PAPERLESS_AUTO_CREATE: "true"
      PAPERLESS_AUTO_LOGIN: "true"
      PAPERLESS_ENABLE_ALLAUTH: "true"
      PAPERLESS_SOCIAL_ACCOUNT_SYNC_GROUPS: "true"
      PAPERLESS_PRE_CONSUME_SCRIPT: /usr/src/paperless/scripts/removepassword.py
    networks:
      - pangolin_net
    healthcheck:
      test: curl -s http://127.0.0.1:8000 > /dev/null || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    depends_on:
      paperless-broker:
        condition: service_healthy

volumes:
  paperless-redis:

networks:
  pangolin_net:
    external: true
